In [31]:
#OBJETIVO
#IDENTIFICAR O MELHOR TIPO DE VINHO E A REGIÃO PARA VENDE-LO E O MAIOR CONCORRENTE NESSA LOCALIDADE COM SEU DEVIDO CUSTO/PREÇO

# Analisar o dataset
# Análise dos tipos de dados do dataset, com a quantidade de registros não nulos, quantidade totais de registros por coluna/feature.

import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import norm

dataset = sns.load_dataset("wine")

#print("Avaliando os dados e a forma dos dados dentro do dataset")
wine =sns.load_dataset("wine")
#print("Listagem de dados do Dataset")
#dataset.info()
#dataset.shape

In [32]:
#VERIFICA REGISTROS NULOS E AVALIANDO SITUAÇÃO DAS FEATURES

# Aqui podemos já detectar uma feature ("region_2region_2") que possui muitos registros nulos, portanto, um canditado para ser 
# avaliado e talvez excluído do dataset.
#Vemos aqui também que a maioria das demais colunas estão com todos os registros não-nulos, ou bem próximo disso, havendo então 
#apenas a necessidade de aplicar alguma lógica para preencher os campos nulos, podendo ser pela média, mediana ou outras alternativas. 

#print("Listando somatório de registros nulos por feature/coluna")

#soma_nulos = pd.read_csv('wine.csv')
#print(dataset.isna().sum())

#Como podemos ver temos então 1 columa "region_2" com mais de 50% dos dados nulos, esta feature para nós não tem valor, tanto pela quantidade de registros nulos
#quanto pelo teor dos dados contidos nela, portanto esta será elimitada.
#Retirar colunas inúteis, como é a coluna de "Unnamed".
#Temos também a feature "designation" com mais de 45mil do 150mil registros nulos. Há aqui a necessidade de identificar se essa feature é importante para a análise,
#caso seja, pensar em uma maneira de substituir os dados nulos. Caso não seja, deverá ser excluída.
#A avaliar qual a melhor decisão mais a frente.

#Existem também outras colunas que possuem alguns poucos registros como null e que precisam ser normalizados.
#Colunas a serem normalizadas: "country", "price", "province" e "region_1".


#dataset.loc('country','points','price','province','region_1','variety','winery')   ## erro nessa linha

#wine1 = dataset[["country","points",'price','province','region_1','variety','winery']].head(100)
#wine1

In [ ]:
#VERIFICAR REGISTROS DUPLICADOS, EXCLUIR REGISTROS E FAZER OS PRIMEIROS TRATAMENTOS

#verificar duplicadas
duplica=dataset.append(dataset[["country","points",'price','province','region_1','variety','winery']])
#dataset.info()
#duplica.info()

#duplica1 = dataset.drop(['Unnamed'], axis=1).columns ##não está funcionando
#duplica1
#duplica.drop_duplicates()
#duplica.info()
#duplica.nlargest(5, 'points', keep='all')







#sns.displot(data=dataset,             x="cut", y="price", col="color");
#duplica=diamonds.append(diamonds)
#dataset.head()


# a fazer ainda
#sns.relplot(data=dataset, x="country", y="points", col="price", hue="variety" ,style="variety")

In [ ]:
#DAQUI PARA BAIXO É SÓ PARA FACILICAR A BUSCA DAS FUNÇÕES, NÃO É PARTE DO TRABALHO

In [7]:
import numpy as np
import seaborn as sns
#from scipy import stats
from scipy.stats import norm
import pandas as pd

diamonds =sns.load_dataset("diamonds")
diamonds.columns
#diamonds.str.upper() 
#diamonds.head() 
#diamonds.columns=[col.upper() for col in diamonds]
#diamonds.columns

diamonds.columns=[col.lower() for col in diamonds]
diamonds.columns

#retorna valores nulos
diamonds.isnull() #não é viavel
diamonds.isnull().sum()
diamonds
diamonds.shape
diamonds

     carat      cut color clarity  depth  table  price     x     y     z
0     0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1     0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2     0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3     0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4     0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
..     ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
352   0.90     Fair     I     SI1   67.3   59.0   2804  5.93  5.84  3.96
353   0.74  Premium     F     VS2   61.7   58.0   2805  5.85  5.78  3.59
354   0.74  Premium     F     VS2   61.9   56.0   2805  5.80  5.77  3.58
355   0.73    Ideal     E     SI2   61.8   58.0   2805  5.77  5.81  3.58
356   0.57     Fair     E    VVS1   58.7   66.0   2805  5.34  5.43  3.16

[357 rows x 10 columns]

In [ ]:
import numpy as np
import seaborn as sns
#from scipy import stats
from scipy.stats import norm
import pandas as pd


#correlação entre colunas / identificar correlacionamentos entre as features 
#quanto mais perto de 1 (+ ou -) maior é a indicação de correlacionamento
diamonds =sns.load_dataset("diamonds")
diamonds.corr()

In [ ]:
import numpy as np
import seaborn as sns
#from scipy import stats
from scipy.stats import norm
import pandas as pd

#fazer split de x até y e apresentar apenas esses valores
diamonds =sns.load_dataset("diamonds")
diamonds.iloc[0:9]
#diamonds.set_index('carat').head(8)


import numpy as np
import seaborn as sns
#from scipy import stats
from scipy.stats import norm
import pandas as pd

#fazer split de x até y e apresentar apenas esses valores
diamonds =sns.load_dataset("diamonds")
diamonds.set_index('cut')
#diamonds.loc('Ideal':'Fair')


import numpy as np
import seaborn as sns
#from scipy import stats
from scipy.stats import norm
import pandas as pd

#fazer split de x até y e apresentar apenas esses valores
diamonds =sns.load_dataset("diamonds")

diamonds1 = diamonds[["x","color","clarity", "price"]].head(100)
#diamonds1 = diamonds['clarity':'price']
diamonds1[(diamonds1['clarity']=='VS1') & (diamonds1['color']=='E')]
#diamonds1[(diamonds1['clarity']=='VS1') | (diamonds1['clarity']=='VVS1')]